"""Pydantic models: the canonical, platform-agnostic data layer."""

from article_craft.models.adaptation import PlatformExport, SocialPost
from article_craft.models.article import (
    ARTICLE_TYPES,
    PLATFORMS,
    Article,
    ArticleFrontmatter,
    Audience,
    AuthorProfile,
    CodeBlock,
    ImageRef,
    Link,
    Section,
)
from article_craft.models.research import (
    SOURCE_TIERS,
    Claim,
    ClaimConflict,
    ClaimStatus,
    ResearchDoc,
    Source,
    SourceTier,
)
from article_craft.models.review import (
    DIMENSION_MAX,
    Dimension,
    DimensionScore,
    EditorialScore,
    HumanContribution,
    PlatformCheck,
    PlatformCheckReport,
    PlatformCheckStatus,
    PublishRecommendation,
    ReviewIssue,
    ReviewResult,
    RuleClass,
    Severity,
    Verdict,
    verdict_for_score,
)
from article_craft.models.voice import WritingProfile

__all__ = [
    "ARTICLE_TYPES",
    "DIMENSION_MAX",
    "PLATFORMS",
    "SOURCE_TIERS",
    "Article",
    "ArticleFrontmatter",
    "Audience",
    "AuthorProfile",
    "Claim",
    "ClaimConflict",
    "ClaimStatus",
    "CodeBlock",
    "Dimension",
    "DimensionScore",
    "EditorialScore",
    "HumanContribution",
    "ImageRef",
    "Link",
    "PlatformCheck",
    "PlatformCheckReport",
    "PlatformCheckStatus",
    "PlatformExport",
    "PublishRecommendation",
    "ResearchDoc",
    "ReviewIssue",
    "ReviewResult",
    "RuleClass",
    "Section",
    "Severity",
    "SocialPost",
    "Source",
    "SourceTier",
    "Verdict",
    "WritingProfile",
    "verdict_for_score",
]
