"""Voice models: the writing profile extracted from the author's own work.

Advisory only. The voice system is intended for the user's own writing; it
must never be used to imitate another person's style from copyrighted
sources.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class WritingProfile(BaseModel):
    """Statistical + stylistic signals from a corpus of the author's articles."""

    files_analyzed: int = 0
    total_words: int = 0

    # Sentence / paragraph rhythm
    avg_sentence_length: float = 0.0
    median_sentence_length: float = 0.0
    long_sentence_ratio: float = 0.0  # fraction of sentences > 35 words
    avg_paragraph_sentences: float = 0.0

    # Voice signals
    first_person_rate: float = 0.0  # "I/my/we/our" per 100 words
    second_person_rate: float = 0.0  # "you/your" per 100 words
    hedging_rate: float = 0.0  # "maybe/perhaps/arguably/..." per 100 words
    adverb_rate: float = 0.0  # "very/really/actually/..." per 100 words

    # Structure signals
    avg_words_per_1000_between_headings: float = 0.0
    heading_style: str = "unknown"  # "sentence case" | "Title Case" | "mixed"
    list_usage_per_1000_words: float = 0.0
    code_blocks_per_1000_words: float = 0.0
    images_per_1000_words: float = 0.0

    # Craft signals
    example_markers_per_1000_words: float = 0.0  # "for example", "e.g.", "suppose"
    analogy_markers_per_1000_words: float = 0.0  # "like", "as if", "think of"
    questions_per_1000_words: float = 0.0

    # Vocabulary
    top_content_words: list[str] = Field(default_factory=list)
    signature_phrases: list[str] = Field(default_factory=list)

    # Derived style labels (heuristic, advisory)
    tone: str = "unknown"  # conversational-technical | formal-technical | personal-narrative
    technical_depth: str = "unknown"  # beginner | intermediate | advanced

    def as_markdown(self) -> str:
        """Render the profile as the human-readable ``.article-craft/voice.md``.

        The profile is advisory: it describes the author's own patterns so the
        agent can help the author sound like *themselves*, never anyone else.
        """
        lines: list[str] = [
            "# Writing Voice Profile",
            "",
            f"_Advisory profile generated by `article-craft learn` from "
            f"{self.files_analyzed} article(s), {self.total_words:,} words._",
            "",
            "## Rhythm",
            "",
            f"- Average sentence length: **{self.avg_sentence_length:.1f} words** "
            f"(median {self.median_sentence_length:.0f})",
            f"- Long sentences (>35 words): **{self.long_sentence_ratio * 100:.0f}%**",
            f"- Average paragraph: **{self.avg_paragraph_sentences:.1f} sentences**",
            "",
            "## Voice signals",
            "",
            f"- First person: **{self.first_person_rate:.1f}** per 100 words",
            f"- Second person (direct address): **{self.second_person_rate:.1f}** per 100 words",
            f"- Hedging: **{self.hedging_rate:.1f}** per 100 words",
            f"- Filler adverbs: **{self.adverb_rate:.1f}** per 100 words",
            f"- Examples: **{self.example_markers_per_1000_words:.1f}** per 1000 words",
            f"- Analogies: **{self.analogy_markers_per_1000_words:.1f}** per 1000 words",
            f"- Questions to reader: **{self.questions_per_1000_words:.1f}** per 1000 words",
            "",
            "## Structure",
            "",
            f"- Average section length: **{self.avg_words_per_1000_between_headings:.0f} words**",
            f"- Heading style: **{self.heading_style}**",
            f"- Lists: **{self.list_usage_per_1000_words:.1f}** per 1000 words",
            f"- Code blocks: **{self.code_blocks_per_1000_words:.1f}** per 1000 words",
            f"- Images: **{self.images_per_1000_words:.1f}** per 1000 words",
            "",
            "## Vocabulary",
            "",
        ]
        if self.top_content_words:
            lines.append(f"- Recurring words: {', '.join(self.top_content_words[:12])}")
        if self.signature_phrases:
            lines.append(f"- Signature phrases: {', '.join(self.signature_phrases[:8])}")
        lines += [
            "",
            "## Derived style (heuristic)",
            "",
            f"- Tone: **{self.tone}**",
            f"- Technical depth: **{self.technical_depth}**",
            "",
            "## How to use this profile",
            "",
            "When drafting or revising for this author, aim for these ranges.",
            "The profile is descriptive of the author's existing work; it is not",
            "a template for imitating anyone else's writing.",
            "",
        ]
        return "\n".join(lines)
